### ISSUE TITLE
Trueshot Aura

### ISSUE THREAD

**Issue by Redrian-Hellscream** [Valhalla-Gaming/Tracker#1488]
http://www.wowhead.com/spell=19506/trueshot-aura
The passive ablity doesn't apply any effect on the hunter or on any party member.

**Comment by Moustachos** [comment]
Fixed in a previous update.

**Comment by Moustachos** [comment]
Ref #2266

**Comment by Redrian-Hellscream** [comment]
Still not working, or at least the buff is not displayed...

**Comment by Tregeta** [comment]
Check to see if you have any other buffs that are increasing your attack power as theirs will override it.

**Comment by Redrian-Hellscream** [comment]
Nope, the hunter is with no other buffs and trueshot is still not present.
It appears in the list only when in a battleground, but not individually.

**Comment by Tregeta** [comment]
Thanks for the additional information

**Comment by Tregeta** [comment]
In light of doing more research on this issue I've found an interesting piece of information:
http://www.wowhead.com/spell=19506/trueshot-aura#comments:id=1770658
This may still hold true

**Comment by Redrian-Hellscream** [comment]
Makes sense now, I suppose you can close the issue now, thanks.
